import{S as b,i}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const w="49617866-877f488ac6d2fa69158bf0643",S="https://pixabay.com/api/",P=15;async function q(e,t=1){const n=new URLSearchParams({key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:P}),a=await fetch(`${S}?${n}`);if(!a.ok)throw new Error(`HTTP error! status: ${a.status}`);return await a.json()}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".loader-more"),v=new b(".gallery a",{captionSelector:"img",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function $(e){if(!Array.isArray(e))return;const t=e.map(({webformatURL:n,largeImageURL:a,tags:r,likes:o,views:s,comments:p,downloads:L})=>`
    <li class="gallery-item">
      <a href="${a}" title="${r}">
        <img src="${n}" alt="${r}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${p}</p>
        <p><b>Downloads:</b> ${L}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),v.refresh()}function E(){f.innerHTML=""}function M(){m.classList.remove("hidden")}function x(){m.classList.add("hidden")}function A(){y.classList.remove("hidden")}function B(){y.classList.add("hidden")}function H(){document.querySelector(".gallery-button").classList.remove("hidden")}function g(){document.querySelector(".gallery-button").classList.add("hidden")}const O=document.querySelector(".gallery-button"),u=document.querySelector(".form");let l="",c=1,d=0;u.addEventListener("submit",async e=>{e.preventDefault();const t=e.target.elements["search-text"].value.trim();if(t!==l&&(l=t,c=1,E(),g()),!t){i.error({message:"Please enter a search term!"});return}await h({isLoadMore:!1}),u.reset()});O.addEventListener("click",async()=>{c+=1,await h({isLoadMore:!0})});async function h({isLoadMore:e}){e?A():M();try{const t=await q(l,c);if(d=t.totalHits,t.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}$(t.hits),c*15>=d?(g(),i.info({message:"We're sorry, but you've reached the end of search results."})):H(),T()}catch(t){console.error("Error fetching images:",t),i.error({message:"Something went wrong. Please try again later."})}finally{e?B():x()}}function T(){const e=document.querySelector(".gallery-item");if(!e)return;const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}document.querySelector(".gallery-button").onmousemove=e=>{const t=e.pageX-e.target.offsetLeft,n=e.pageY-e.target.offsetTop;e.target.style.setProperty("--x",`${t}px`),e.target.style.setProperty("--y",`${n}px`)};
//# sourceMappingURL=index.js.map
