import{S as L,i}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const b="49617866-877f488ac6d2fa69158bf0643",w="https://pixabay.com/api/",S=15;async function P(e,r=1){const n=new URLSearchParams({key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:S}),a=await fetch(`${w}?${n}`);if(!a.ok)throw new Error(`HTTP error! status: ${a.status}`);return await a.json()}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".loader-more"),v=new L(".gallery a",{captionSelector:"img",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function q(e){const r=e.map(({webformatURL:n,largeImageURL:a,tags:t,likes:o,views:s,comments:h,downloads:p})=>`
    <li class="gallery-item">
      <a href="${a}">
        <img src="${n}" alt="${t}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${h}</p>
        <p><b>Downloads:</b> ${p}</p>
      </div>
    </li>
  `).join("");u.insertAdjacentHTML("beforeend",r),v.refresh()}function $(){u.innerHTML=""}function E(){m.classList.remove("hidden")}function x(){console.log("hide Loader"),m.classList.add("hidden")}function M(){console.log("show more Loader"),f.classList.remove("hidden")}function B(){console.log("hide more Loader"),f.classList.add("hidden")}function H(){document.querySelector(".gallery-button").classList.remove("hidden")}function y(){document.querySelector(".gallery-button").classList.add("hidden")}const O=document.querySelector(".gallery-button"),T=document.querySelector(".form");let l="",c=1,d=0;T.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements["search-text"].value.trim(),!l){i.error({message:"Please enter a search term!"});return}c=1,$(),y(),await g()});O.addEventListener("click",async()=>{c+=1,await g()});async function g(){E(),M();try{const e=await P(l,c);if(d=e.totalHits,e.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}q(e.hits),c*15>=d?(y(),i.info({message:"We're sorry, but you've reached the end of search results."})):H(),A()}catch(e){console.error("Error fetching images:",e),i.error({message:"Something went wrong. Please try again later."})}finally{x(),B()}}function A(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}document.querySelector(".gallery-button").onmousemove=e=>{const r=e.pageX-e.target.offsetLeft,n=e.pageY-e.target.offsetTop;e.target.style.setProperty("--x",`${r}px`),e.target.style.setProperty("--y",`${n}px`)};
//# sourceMappingURL=index.js.map
