import{S as g,i}from"./assets/vendor-5ObWk2rO.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const p="49617866-877f488ac6d2fa69158bf0643",b="https://pixabay.com/api/",L=15;async function w(t,a=1){const n=new URLSearchParams({key:p,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:L}),o=await fetch(`${b}?${n}`);if(!o.ok)throw new Error(`HTTP error! status: ${o.status}`);return await o.json()}const d=document.querySelector(".gallery");document.querySelector(".loader");const S=new g(".gallery a",{captionSelector:"img",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function P(t){const a=t.map(({webformatURL:n,largeImageURL:o,tags:e,likes:r,views:s,comments:y,downloads:h})=>`
    <li class="gallery-item">
      <a href="${o}">
        <img src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${y}</p>
        <p><b>Downloads:</b> ${h}</p>
      </div>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",a),S.refresh()}function q(){d.innerHTML=""}function v(){document.querySelector(".loader").classList.remove("hidden")}function $(){document.querySelector(".loader").classList.add("hidden")}function E(){document.querySelector(".gallery-button").classList.remove("hidden")}function m(){document.querySelector(".gallery-button").classList.add("hidden")}const B=document.querySelector(".gallery-button"),H=document.querySelector(".form");let l="",c=1,u=0;H.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements["search-text"].value.trim(),!l){i.error({message:"Please enter a search term!"});return}c=1,q(),m(),await f()});B.addEventListener("click",async()=>{c+=1,await f()});async function f(){v();try{const t=await w(l,c);if(u=t.totalHits,t.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}P(t.hits),c*15>=u?(m(),i.info({message:"We're sorry, but you've reached the end of search results."})):E(),M()}catch(t){console.error("Error fetching images:",t),i.error({message:"Something went wrong. Please try again later."})}finally{$()}}function M(){const{heigth:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
